import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import Dashboard from "@/components/dashboard";
import Providers from './Providers'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next Chat IA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="absolute top-0 z-[-2] h-screen w-screen bg-white bg-[radial-gradient(100%_50%_at_50%_0%,rgba(0,163,255,0.13)_0,rgba(0,163,255,0)_50%,rgba(0,163,255,0)_100%)]"></div>
          <div className="grid gap-6">
            <Header />
            <div className="grid grid-cols-8 gap-2">
              <Dashboard />
              <div className="col-start-2 col-end-9">
                {children}
              </div>
            </div>
          </div>
          {/*<footer>
            <Footer />
          </footer>*/}
        </Providers>
      </body>
    </html>
  );
}
